---
name: mp3info
version: 1.06
author:
  - Johan Vromans <jvromans@squirrel.nl>
abstract: prints MP3 header info
license: perl
requires:
  Getopt::Long: 2.33
  MP3::Info: 1.02
build_requires:
  Test::More: 0
generated_by: Module::Build version 0.28
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
resources:
  license: http://dev.perl.org/licenses/
